type = "mod"; 
name = "MadWolfs-ItemRework";
picture = "@Madwolfs-ItemRework/addons/Attributes_Edits/gui/imagesets/MW_logo.paa";
logoSmall = "@Madwolfs-ItemRework/addons/Attributes_Edits/gui/imagesets";
logo = "@Madwolfs-ItemRework/addons/Attributes_Edits/gui/imagesets/MW_logo.paa";
logoOver = "@Madwolfs-ItemRework/addons/Attributes_Edits/gui/imagesets/MW_logo.paa";
tooltip = "tooltip";
overview = "Just Some Things I Put Together";
action = "https://steamcommunity.com/sharedfiles/filedetails/?id=2685445852";
author = "Madwolf";
version = "1.0";